name: Dockerized .NET Build with Categorized Annotations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  categorized-annotations:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install .NET SDK
      - name: Install .NET SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-7.0

      ### DOTNET PUBLISH ANNOTATIONS ###
      - name: DotNet Publish with Logs Capture
        id: publish
        run: |
          echo "Starting publish..."
          dotnet publish -c Release -o ./publish_output > publish.log 2>&1 || true
        continue-on-error: true

      - name: Parse Publish Logs for Annotations
        id: publish_status
        run: |
          while IFS= read -r line; do
            if echo "$line" | grep -q "warning"; then
              file=$(echo "$line" | awk -F':' '{print $1}')
              line_num=$(echo "$line" | awk -F':' '{print $2}')
              message=$(echo "$line" | cut -d':' -f4-)
              echo "::warning title=build_status,file=$file,line=$line_num::$message"
            elif echo "$line" | grep -q "error"; then
              file=$(echo "$line" | awk -F':' '{print $1}')
              line_num=$(echo "$line" | awk -F':' '{print $2}')
              message=$(echo "$line" | cut -d':' -f4-)
              echo "::error title=build_status,file=$file,line=$line_num::$message"
            fi
          done < publish.log || true

      ### LINT ANNOTATIONS ###
      - name: Run Linter and Capture Logs
        id: lint
        run: |
          dotnet format --check --verbosity detailed > lint.log 2>&1 || true

      - name: Parse Lint Logs for Annotations
        id: lint_status
        run: |
          while IFS= read -r line; do
            if echo "$line" | grep -q "warning"; then
              echo "::warning title=lint::$line"
            elif echo "$line" | grep -q "error"; then
              echo "::error title=lint::$line"
            fi
          done < lint.log || true

      ### TEST ANNOTATIONS ###
      - name: Run Tests and Save Results
        id: test
        run: |
          mkdir -p test-results
          dotnet test --logger:"junit;LogFilePath=test-results/test-results.xml" || true

      - name: Annotate Test Failures
        uses: scacap/action-surefire-report@v1
        with:
          paths: test-results/test-results.xml
          title: Test

      ### VERIFY WORKFLOW SUCCESS ###
      - name: Verify Workflow Success
        run: |
          if grep "error" lint.log || grep "error" build.log || grep "Failed" test-results/test-results.xml; then
            echo "Errors detected. Please resolve them."
            exit 1
          fi
