name: Dockerized .NET Build with Categorized Annotations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  categorized-annotations:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install .NET SDK
      - name: Install .NET SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-7.0

      ### DOTNET PUBLISH ANNOTATIONS ###
      - name: DotNet Publish with Logs Capture
        id: publish
        run: |
          echo "Starting publish..."
          dotnet publish -c Release -o ./publish_output > publish.log 2>&1 || true
        continue-on-error: true

      - name: Publish Status
        id: publish_status
        run: |
          while IFS= read -r line; do
            if echo "$line" | grep -q "warning"; then
              file=$(echo "$line" | awk -F':' '{print $1}')
              line_num=$(echo "$line" | awk -F':' '{print $2}')
              message=$(echo "$line"
